services:
  - type: web
    name: libretranslate
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT main:main
    envVars:
      - key: PORT
        value: 10000
      - key: LT_LOAD_ONLY
        value: en,es,fr  # Only load English, Spanish, French
      # - key: LT_API_KEYS
      #   value: secret-api-key  # (optional) – enable API keys
